name: Lint

on:
  schedule:
    - cron: '0 */6 * * *'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '18.x'
          registry-url: https://registry.npmjs.org/
      - name: Install dependencies
        run: npm ci
      - name: Run renovate
        run: npm run renovate -- trevinhofmann/eslint-config-principled
